// scripts/gen-api.mjs
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import openapiTS, { astToString } from "openapi-typescript";

const OPENAPI_URL =
  process.env.OPENAPI_URL || "http://localhost:8080/swagger/v1/swagger.json";

const outDir = path.join(process.cwd(), "src", "lib", "api", "generated");
const outFile = path.join(outDir, "openapi.ts");

const banner = `/* eslint-disable */
/**
 * DO NOT EDIT THIS FILE BY HAND.
 * Generated by \`npm run gen:api\` from the backend OpenAPI spec.
 * Source: ${OPENAPI_URL}
 */
`;

async function main() {
  console.log(`Generating OpenAPI types from: ${OPENAPI_URL}`);

  const res = await fetch(OPENAPI_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch OpenAPI spec: ${res.status} ${res.statusText}`
    );
  }

  const spec = await res.json();

  // In some versions, openapi-typescript returns an AST (array of nodes)
  const ast = await openapiTS(spec);

  // Convert AST -> TS source
  const tsSource =
    typeof ast === "string" ? ast : astToString(ast);

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(outFile, `${banner}\n${tsSource}\n`, "utf8");

  console.log(`Wrote: ${path.relative(process.cwd(), outFile)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});